// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQF68kEq52JCOZyTq7UIN3MUO7as1Vgos',
    appId: '1:493357910485:web:b41e2dce87878362c5155c',
    messagingSenderId: '493357910485',
    projectId: 'tfg-amanda',
    authDomain: 'tfg-amanda.firebaseapp.com',
    storageBucket: 'tfg-amanda.firebasestorage.app',
    measurementId: 'G-BGT7Y9V7V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHnyX5OFwP3IwotGxV5slcmM5vi03FAs8',
    appId: '1:493357910485:android:386a01e3f1a7fd16c5155c',
    messagingSenderId: '493357910485',
    projectId: 'tfg-amanda',
    storageBucket: 'tfg-amanda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqIyXdP2q2TlzQDzKFll41Uj-dhm9ngsc',
    appId: '1:493357910485:ios:6aa7b331ab8bae6fc5155c',
    messagingSenderId: '493357910485',
    projectId: 'tfg-amanda',
    storageBucket: 'tfg-amanda.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2210',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqIyXdP2q2TlzQDzKFll41Uj-dhm9ngsc',
    appId: '1:493357910485:ios:05c4b622ba3d2209c5155c',
    messagingSenderId: '493357910485',
    projectId: 'tfg-amanda',
    storageBucket: 'tfg-amanda.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQF68kEq52JCOZyTq7UIN3MUO7as1Vgos',
    appId: '1:493357910485:web:3459632f962e0b6cc5155c',
    messagingSenderId: '493357910485',
    projectId: 'tfg-amanda',
    authDomain: 'tfg-amanda.firebaseapp.com',
    storageBucket: 'tfg-amanda.firebasestorage.app',
    measurementId: 'G-HNNVJ258VX',
  );
}
